version: '3.3'
services:
  web:
    image: atlassian/confluence-server:8.5.3
    ports:
      - "8092:8090"
      - "5008:5008"
      - "5005:5005"
    depends_on:
      - db
    environment:
      - CATALINA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5008
  db:
    image: postgres:12.8-alpine
    ports:
      - "5555:5432"
    environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=confluence